### ISSUE TITLE
Retrieve summary for  query

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/sequel_impala#23]
Just like we record the profile for a query (#3), we should also record the summary for a query as well.

**Comment by jeremyevans** [comment]
Looking at Impala's documentation (https://www.cloudera.com/documentation/enterprise/5-9-x/topics/impala_explain_plan.html#perf_summary), the SUMMARY statement is only available to `impala-shell` and not available via the Impala SQL interface.  However, the documentation mentions that the SUMMARY output is also available directly inside the query profile.  That appears to be accurate, here's an extract for a query profile for a `SELECT count(*) AS count from table` query for a table with 1.56M rows:

```
    ExecSummary: 
Operator       #Hosts   Avg Time   Max Time  #Rows  Est. #Rows   Peak Mem  Est. Peak Mem  Detail             
-------------------------------------------------------------------------------------------------------------
03:AGGREGATE        1  234.002ms  234.002ms      1           1   20.00 KB        -1.00 B  FINALIZE           
02:EXCHANGE         1    0.000ns    0.000ns      2           1          0        -1.00 B  UNPARTITIONED      
01:AGGREGATE        2  161.499ms  164.001ms      2           1   12.00 KB       10.00 MB                     
00:SCAN HDFS        2    3.000ms    4.000ms  1.56M          -1  572.00 KB              0  table
    Errors: 
```

Since the profiling information already includes the summary information between the `ExecSummary:` and `Errors:` lines, I conclude that this issue can be closed, unless you would like to add a Database method that just tries to extract the summary information from the profile output.

**Comment by jenniferduryea** [comment]
@aguynamedryan is this still an issue?

**Comment by aguynamedryan** [comment]
@jenniferduryea, we're good here.
